---
- name: Include OS-family specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include distribution specific install tasks
  ansible.builtin.include_tasks: "install-{{ ansible_os_family }}-family.yml"

- name: Create /var/log/smartd directory
  become: true
  ansible.builtin.file:
    path: /var/log/smartd
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy smartmontools configuration file
  become: true
  ansible.builtin.copy:
    src: "{{ smartd_defaults_src }}"
    dest: "{{ smartd_defaults_file }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart smartd service

- name: Copy smartd configuration file
  become: true
  ansible.builtin.template:
    src: smartd.conf.j2
    dest: /etc/smartd.conf
    owner: root
    group: root
    mode: 0644
  when: smartd_configure | bool or smartd_devices | length > 0
  notify: Restart smartd service

- name: Manage smartd service
  become: true
  ansible.builtin.service:
    name: "{{ smartd_service_name }}"
    state: started
    enabled: true
