---
- name: Restart leaf service
  become: true
  ansible.builtin.service:
    name: "{{ leaf_service_name }}"
    state: restarted
  register: result
  until: result["status"]["ActiveState"] == "active"
  retries: 10
  delay: 20
