---
- name: Restart wazuh_proxy service
  become: true
  ansible.builtin.service:
    name: "{{ wazuh_proxy_service_name }}"
    state: restarted
  register: result
  until: result["status"]["ActiveState"] == "active"
  retries: 10
  delay: 20
