---
- name: Restart dnsmasq service
  become: true
  ansible.builtin.systemd_service:
    name: "{{ dnsmasq_service_name }}"
    state: restarted
  when:
    - _dnsmasq_service_restart | default(true) | bool
  notify:
    - Wait until dnsmasq service is active

- name: Wait until dnsmasq service is active
  become: true
  ansible.builtin.command:
    cmd: "systemctl is-active {{ dnsmasq_service_name }}"
  register: _dnsmasq_is_active
  changed_when: false
  failed_when: false
  until: _dnsmasq_is_active.stdout | trim == "active"
  retries: 10
  delay: 20
  notify:
    - Register that dnsmasq service was restarted

- name: Register that dnsmasq service was restarted
  ansible.builtin.set_fact:
    _dnsmasq_service_restart: false
