---
- name: Create required directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0755
  loop:
    - "{{ adminer_docker_compose_directory }}"

- name: Copy docker-compose.yml file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ adminer_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
  notify: Restart adminer service

- name: Manage adminer service
  become: true
  ansible.builtin.systemd_service:
    name: "{{ adminer_service_name }}"
    state: started
    enabled: true

- name: Wait until adminer service is active
  become: true
  ansible.builtin.command:
    cmd: "systemctl is-active {{ adminer_service_name }}"
  register: _adminer_is_active
  changed_when: false
  failed_when: false
  until: _adminer_is_active.stdout | trim == "active"
  retries: 10
  delay: 20
